# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
  condition: eq(false, true)
- script: npm install --production
  displayName: 'npm install dependencies'
  condition: eq(false, true)
- script: npm run build
  displayName: 'npm build react app and proxy'
  condition: eq(false, true)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  condition: eq(false, true)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/api'
  condition: eq(false, true)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: eq(false, true)
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'build'
    api_location: '/api'
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)