# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install --production
  displayName: 'npm install dependencies'
  condition: eq(false, true)
- script: npm run build
  displayName: 'npm build react app and proxy'
  condition: eq(false, true)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  condition: eq(false, true)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/api'
  condition: eq(false, true)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'build'
    api_location: '/api'
    azure_static_web_apps_api_token: 'ae0371e33bb9600b69fe7bd62a4812b6f4ad0c3c09c0537649ff61e49cb05e761-c96fe1cf-f72d-42f6-b5d8-fe1e5739a1f500369359'